spring.application.name=Turism
server.port=8085
spring.config.import=optional:file:../.env[.properties]

ticketmaster.api.base-url=https://app.ticketmaster.com/discovery/v2
ticketmaster.api.key=${TICKETMASTER_API_KEY:}
ticketmaster.api.default-country-code=

google.places.base-url=https://serpapi.com/search.json
google.places.key=${GOOGLE_PLACES_API_KEY:${SERPAPI_API_KEY:}}
google.places.default-language=ro

