spring.application.name=Weather
server.port=8082

# Visual Crossing API
visualcrossing.api.key=${VISUAL_CROSSING_API_KEY:YOUR_API_KEY_HERE}
visualcrossing.api.base-url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
