package com.licenta.games;

import com.licenta.games.entity.Zone;
import com.licenta.games.repository.ZoneRepository;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class ZoneSeeder implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(ZoneSeeder.class);
    private final ZoneRepository zoneRepository;

    @Override
    public void run(String... args) {
        if (zoneRepository.count() > 0) {
            log.info("Zones already seeded, skipping.");
            return;
        }

        List<Zone> zones = List.of(
            zone("Paris", "Europe", 48.8566, 2.3522, 48.81, 2.25, 48.90, 2.42, "The City of Light, Paris is home to the iconic Eiffel Tower, built in 1889 by Gustave Eiffel. The city sits on the Seine River and was historically known as Lutetia. Paris hosts the Louvre, the world's most visited museum, which contains over 35,000 works of art including the Mona Lisa.", 1, "🗼"),
            zone("Tokyo", "Asia", 35.6762, 139.6503, 35.53, 139.44, 35.82, 139.93, "Tokyo is Japan's bustling capital, the most populous metropolitan area on Earth. Mount Fuji, Japan's iconic volcano, is visible from the city on clear days. The city is known for its blend of ultramodern technology and traditional culture, including ancient temples like Senso-ji in Asakusa.", 1, "🗾"),
            zone("New York", "North America", 40.7128, -74.0060, 40.47, -74.26, 40.92, -73.69, "New York City, the 'Big Apple', is the most populous city in the United States. The Statue of Liberty, a gift from France in 1886, stands in New York Harbor. The city's iconic skyline features the Empire State Building and Central Park stretches 2.5 miles through Manhattan.", 1, "🗽"),
            zone("London", "Europe", 51.5074, -0.1278, 51.38, -0.35, 51.67, 0.15, "London, the capital of England, spans the River Thames. Big Ben, the iconic clock tower, is part of the Palace of Westminster. The city served as the heart of the British Empire, which at its peak covered about 24% of the world's land area. The Greenwich Prime Meridian passes through the city.", 1, "🎡"),
            zone("Sydney", "Oceania", -33.8688, 151.2093, -34.17, 150.52, -33.43, 151.34, "Sydney is Australia's largest city and home to the iconic Sydney Opera House, designed by Danish architect Jørn Utzon. Sydney Harbour Bridge, nicknamed 'The Coathanger', stretches 1,149 meters. The city was established as a British penal colony in 1788 and hosted the 2000 Summer Olympics.", 1, "🦘"),
            zone("Rio de Janeiro", "South America", -22.9068, -43.1729, -23.08, -43.79, -22.74, -43.10, "Rio de Janeiro is famous for Christ the Redeemer statue atop Corcovado Mountain, declared one of the New Seven Wonders of the World. The city hosts the world's most famous Carnival celebration. Copacabana and Ipanema beaches stretch along its Atlantic coast. Sugarloaf Mountain rises 396 meters above Guanabara Bay.", 1, "🏖️"),
            zone("Cairo", "Africa", 30.0444, 31.2357, 29.85, 31.13, 30.25, 31.45, "Cairo, Egypt's capital, is home to the last surviving Wonder of the Ancient World – the Great Pyramid of Giza. The Sphinx guards these ancient tombs near the city. The Nile River, the world's longest river, flows through Cairo. The city contains the Egyptian Museum with over 120,000 artifacts.", 1, "🏺"),
            zone("Moscow", "Europe", 55.7558, 37.6173, 55.49, 37.32, 56.01, 37.97, "Moscow is Russia's capital and largest city. The Kremlin, a historic fortified complex, serves as the official residence of the Russian President. Red Square is home to St. Basil's Cathedral with its distinctive colorful onion domes. The Moscow Metro is famous for its ornate stations, often called 'underground palaces'.", 2, "🏛️"),
            zone("Beijing", "Asia", 39.9042, 116.4074, 39.44, 116.01, 40.59, 116.79, "Beijing, China's capital for over 800 years, contains the Forbidden City – a palace complex that served as the home of Chinese emperors. The Great Wall of China stretches across mountains north of the city. Tiananmen Square is the world's largest public square. The city hosted the Summer Olympics in 2008 and Winter Olympics in 2022.", 2, "🏯"),
            zone("Mumbai", "Asia", 19.0760, 72.8777, 18.89, 72.77, 19.27, 72.98, "Mumbai is India's financial capital and most populous city. The Gateway of India, built in 1924, stands at the harbor where the British Raj's viceroys first landed. Bollywood, the world's largest film industry by ticket sales, is centered here. The city's Dharavi is one of Asia's largest urban slums, home to a thriving informal economy.", 2, "🎬"),
            zone("Buenos Aires", "South America", -34.6037, -58.3816, -34.72, -58.54, -34.52, -58.33, "Buenos Aires, Argentina's capital, is called the 'Paris of South America' for its European-style architecture. The city is the birthplace of the tango dance. La Boca neighborhood features colorful corrugated iron buildings. The iconic Obelisco de Buenos Aires stands at the intersection of Corrientes and 9 de Julio, the world's widest avenue.", 2, "💃"),
            zone("Istanbul", "Europe", 41.0082, 28.9784, 40.80, 28.44, 41.32, 29.23, "Istanbul is the only city in the world that spans two continents – Europe and Asia, divided by the Bosphorus strait. Hagia Sophia served as a cathedral, mosque, and museum across its history. The Grand Bazaar is one of the world's oldest and largest covered markets. Constantinople was the capital of the Byzantine and Ottoman Empires.", 2, "🕌"),
            zone("Nairobi", "Africa", -1.2921, 36.8219, -1.44, 36.66, -1.16, 36.98, "Nairobi is Kenya's capital and Africa's fourth largest city. Nairobi National Park is the only national park in the world situated within a capital city, where lions roam with the city skyline as backdrop. The city sits at 1,795 meters above sea level. Karen Blixen, author of 'Out of Africa', lived near the city.", 2, "🦁"),
            zone("Mexico City", "North America", 19.4326, -99.1332, 19.21, -99.37, 19.59, -99.00, "Mexico City, one of the world's largest cities, is built on the ancient Aztec capital of Tenochtitlan, which sat in the middle of a lake. The Metropolitan Cathedral took 250 years to build. Xochimilco's floating gardens (chinampas) date back to Aztec times. The city sinks annually due to its lake bed foundation.", 2, "🦅"),
            zone("Athens", "Europe", 37.9838, 23.7275, 37.82, 23.59, 38.13, 23.86, "Athens is the birthplace of democracy, philosophy, and the Olympic Games. The Acropolis, crowned by the Parthenon temple, overlooks the city. Socrates, Plato, and Aristotle walked these streets. Athens is one of the world's oldest cities with a recorded history spanning 3,400 years.", 2, "🏛️"),
            zone("Cape Town", "Africa", -33.9249, 18.4241, -34.36, 18.28, -33.47, 18.96, "Cape Town sits at the foot of Table Mountain, one of the world's oldest mountains at 600 million years old. Nearby Cape of Good Hope was once thought to be the southernmost point of Africa. Robben Island, visible from the city, is where Nelson Mandela was imprisoned for 18 years. The Cape Floral Kingdom is one of Earth's six floral kingdoms.", 2, "🌿"),
            zone("Machu Picchu", "South America", -13.1631, -72.5450, -13.22, -72.60, -13.10, -72.50, "Machu Picchu is a 15th-century Inca citadel perched at 2,430 meters in the Andes Mountains of Peru. Built around 1450 AD, it was abandoned a century later during the Spanish Conquest and unknown to the outside world until 1911. The site consists of 200 structures using a technique called ashlar – stones fitted together without mortar.", 3, "🏔️"),
            zone("Sahara Desert", "Africa", 23.0, 12.0, 14.0, -18.0, 37.5, 42.0, "The Sahara is the world's largest hot desert, covering 9.2 million km² – almost the size of the United States. Contrary to popular belief, only about 25% of the Sahara is sand. Rock and gravel plains dominate. The Sahara was green and humid just 5,000-10,000 years ago during the African Humid Period. Sand dunes called ergs can reach 180 meters high.", 3, "🏜️"),
            zone("Amazon Rainforest", "South America", -3.4653, -62.2159, -20.0, -80.0, 8.0, -44.0, "The Amazon Rainforest spans 5.5 million km² across nine countries, representing over half of the world's remaining rainforests. It produces 20% of the world's oxygen and contains 10% of all species on Earth. The Amazon River discharges 20% of all fresh water flowing into the world's oceans. Threats from deforestation could turn parts of it into savanna.", 3, "🌿"),
            zone("Antarctica", "Antarctica", -90.0, 0.0, -90.0, -180.0, -60.0, 180.0, "Antarctica is the coldest, windiest, and driest continent on Earth. It holds 70% of the world's fresh water in its ice sheet. The lowest temperature ever recorded on Earth (-89.2°C) was measured here. No country owns Antarctica under the Antarctic Treaty of 1959. Despite hostile conditions, the continent has no permanent human population but hosts scientific research stations.", 3, "🧊"),
            zone("Greenland", "North America", 71.7069, -42.6043, 59.8, -73.0, 83.6, -11.3, "Greenland is the world's largest island, covering 2.1 million km². Despite its name, 80% of the island is covered by an ice sheet up to 3 km thick. It's a self-governing territory of Denmark, though geographically part of North America. If Greenland's ice sheet melted entirely, global sea levels would rise by about 7 meters.", 3, "🧊"),
            zone("Himalaya Mountains", "Asia", 27.9878, 86.9250, 26.0, 72.0, 36.0, 97.0, "The Himalayas are Earth's highest mountain range, containing all 14 peaks above 8,000 meters (the 'Eight-thousanders'). Mount Everest stands at 8,849 meters. The range was formed when the Indian subcontinent collided with Eurasia approximately 50 million years ago. The mountains are still growing by about 5mm per year.", 3, "🏔️"),
            zone("Great Barrier Reef", "Oceania", -18.2871, 147.6992, -24.0, 142.5, -10.0, 154.0, "The Great Barrier Reef is the world's largest coral reef system, stretching 2,300 km off Queensland, Australia. It's so large it's visible from space. The reef contains over 600 types of coral, 1,625 species of fish, and 3,000 species of mollusks. Climate change-induced coral bleaching has damaged over 50% of the reef since 2016.", 3, "🐠"),
            zone("Serengeti", "Africa", -2.3333, 34.8333, -3.5, 33.9, -1.0, 35.9, "The Serengeti ecosystem in Tanzania covers 30,000 km² and hosts the world's largest terrestrial mammal migration. Over 1.5 million wildebeest cross the Mara River annually alongside 250,000 zebras. The name 'Serengeti' comes from the Maasai word 'Siringet', meaning 'the place where the land runs on forever'. Over 70 large mammal species live here.", 3, "🦒"),
            zone("Iceland", "Europe", 64.9631, -19.0208, 63.2, -24.6, 66.6, -13.2, "Iceland sits on the Mid-Atlantic Ridge where the Eurasian and North American tectonic plates meet. The island has 130 volcanic mountains, 30 active volcanic systems, and thousands of hot springs and geysers. The word 'geyser' comes from Iceland's Geysir. Northern Lights are visible from September to March. Iceland runs on 100% renewable energy.", 2, "🌋"),
            zone("Venice", "Europe", 45.4408, 12.3155, 45.32, 12.18, 45.56, 12.48, "Venice is built on 118 small islands connected by 400 bridges over 150 canals. The city has no roads – people travel by gondola, vaporetto (water bus), or on foot. Venice was the most powerful trading republic in medieval Europe, controlling the Mediterranean trade routes. The city is sinking about 1-2mm per year due to its wood pile foundations.", 2, "🚣"),
            zone("Petra", "Asia", 30.3285, 35.4444, 30.25, 35.36, 30.40, 35.56, "Petra is a famous archaeological city in southern Jordan, carved into rose-red sandstone cliffs. Known as the 'Rose City', it was the capital of the Nabataean Kingdom from the 4th century BC. The Treasury (Al-Khazneh), carved around 300 BC, appears in Indiana Jones and the Last Crusade. The city was rediscovered by Western explorers in 1812.", 3, "🏺"),
            zone("Angkor Wat", "Asia", 13.4125, 103.8670, 13.35, 103.79, 13.47, 103.94, "Angkor Wat is the world's largest religious monument, covering 162.6 hectares in Cambodia. Built in the early 12th century by Khmer King Suryavarman II, it was dedicated to the Hindu god Vishnu. The temple later became Buddhist. Its image appears on the Cambodian national flag. The entire Angkor complex may have housed 1 million people at its peak.", 3, "⛩️"),
            zone("Kilimanjaro", "Africa", -3.0674, 37.3556, -3.25, 37.15, -2.83, 37.72, "Mount Kilimanjaro is Africa's highest peak at 5,895 meters and the world's tallest free-standing volcano. Located in Tanzania near the Kenyan border, it has three volcanic cones: Kibo, Mawenzi, and Shira. Despite being near the equator, its summit has glaciers, though they've shrunk by over 80% since 1912 due to climate change.", 3, "🗻"),
            zone("Marrakech", "Africa", 31.6295, -7.9811, 31.52, -8.09, 31.74, -7.87, "Marrakech, the 'Red City', is Morocco's fourth largest city known for its medieval architecture of pink sandstone. The Djemaa el-Fna square is a UNESCO Masterpiece of the Oral and Intangible Heritage of Humanity. The city's medina (old city) dates to the 11th century. The Majorelle Garden was designed by French painter Jacques Majorelle.", 2, "🕌"),
            zone("Reykjavik", "Europe", 64.1355, -21.8954, 63.95, -22.45, 64.32, -21.35, "Reykjavik is the northernmost capital city of a sovereign state in the world. Located in Iceland, it runs almost entirely on geothermal energy. The city is known as the Land of Fire and Ice. The Hallgrímskirkja church, inspired by Icelandic lava flows, is the tallest building in Iceland at 74.5 meters. The midnight sun occurs here in June.", 2, "🌊"),
            zone("Zanzibar", "Africa", -6.1659, 39.2026, -6.51, 39.09, -5.73, 39.72, "Zanzibar is a semi-autonomous archipelago of Tanzania in the Indian Ocean. Stone Town, its historic center, reflects 1,000 years of Swahili, Arab, Indian, and European influences. The spice trade made it one of the most important trading centers in the Indian Ocean world. Freddie Mercury, lead singer of Queen, was born here in 1946.", 2, "🌴"),
            zone("Bali", "Asia", -8.3405, 115.0920, -8.85, 114.43, -8.06, 115.71, "Bali is an Indonesian island known as the 'Island of the Gods' for its 20,000 temples. The Balinese calendar is based on a complex system of lunar-solar cycles. Rice cultivation here uses an ancient irrigation system called subak, a UNESCO World Heritage practice. Bali sits in the 'Ring of Fire' and Mount Agung last erupted in 2018.", 1, "🌺"),
            zone("Prague", "Europe", 50.0755, 14.4378, 49.97, 14.22, 50.18, 14.71, "Prague, the 'City of a Hundred Spires', is the capital of the Czech Republic. Charles Bridge, built in 1357, features 30 Baroque statues of saints. The Old Town Square contains an Astronomical Clock from 1410, the third oldest functioning astronomical clock in the world. Prague Castle is the largest ancient castle in the world by area.", 1, "🏰"),
            zone("Dubrovnik", "Europe", 42.6507, 18.0944, 42.60, 18.01, 42.72, 18.18, "Dubrovnik, Croatia, is known as the 'Pearl of the Adriatic'. Its Old Town is entirely surrounded by massive stone walls built in the 13th century. The city's medieval architecture made it a filming location for King's Landing in Game of Thrones. The city was a powerful maritime republic called Ragusa from the 14th to 19th centuries.", 2, "⚔️"),
            zone("Santorini", "Europe", 36.3932, 25.4615, 36.32, 25.35, 36.47, 25.55, "Santorini is a Greek island in the Aegean Sea, famous for its white-washed buildings with blue domes. The island is the remains of a volcanic caldera – one of the largest volcanic eruptions in recorded history occurred here around 1600 BC, possibly inspiring the Atlantis legend. The sunset from Oia village is considered one of the most beautiful in the world.", 1, "🌅"),
            zone("Angkor Tom", "Asia", 13.4432, 103.8593, 13.40, 103.83, 13.48, 103.90, "Angkor Thom was the last capital of the Khmer Empire, built around 1190 AD by King Jayavarman VII. The city covered 9 km² and may have housed up to 150,000 people, making it one of the largest pre-industrial cities. The Bayon temple at its center features over 200 carved stone faces. The Terrace of the Elephants stretched 350 meters.", 3, "🏛️"),
            zone("Ayers Rock", "Oceania", -25.3444, 131.0369, -25.42, 130.94, -25.25, 131.17, "Uluru (Ayers Rock) is a massive sandstone monolith in the Northern Territory of Australia, rising 348 meters from the desert floor. It's sacred to the Anangu, the local Aboriginal Australians, who have lived in the area for over 10,000 years. The rock is known for changing colors at sunrise and sunset, from orange to deep red to purple.", 2, "🪨"),
            zone("Fjords of Norway", "Europe", 60.4720, 6.5532, 56.0, 3.0, 71.5, 31.0, "Norway's fjords were carved by glaciers during the last Ice Age, 10,000 years ago. Sognefjord is the world's deepest fjord at 1,308 meters and 204 km long. The Norse Vikings who sailed these fjords became some of history's greatest explorers, reaching North America 500 years before Columbus. Norway's fjord landscape is on UNESCO's World Heritage list.", 2, "🛶"),
            zone("Serengeti Migration", "Africa", -1.5, 35.0, -3.5, 33.9, 1.5, 36.5, "The Great Migration of the Serengeti is the largest overland migration on Earth. Over 2 million animals – wildebeest, zebras, gazelles – travel 1,800 km in a circular route following rains and fresh grass. The Mara River crossing is the most dangerous part, where hundreds of Nile crocodiles wait. This cycle of life has continued for millions of years.", 3, "🦬"),
            zone("Patagonia", "South America", -51.6230, -69.2168, -56.0, -76.0, -39.0, -63.0, "Patagonia spans the southern end of South America, shared between Chile and Argentina. Torres del Paine National Park contains dramatic granite peaks and turquoise lakes. The region has the largest ice field outside of the polar regions – the Patagonian Ice Field. The name 'Patagonia' comes from Spanish explorers who encountered indigenous people with large foot coverings.", 3, "🏔️")
        );

        zoneRepository.saveAll(zones);
        log.info("Seeded {} zones.", zones.size());
    }

    private Zone zone(String name, String continent, double lat, double lng,
                      double south, double west, double north, double east,
                      String description, int difficulty, String emoji) {
        return Zone.builder()
                .name(name)
                .continent(continent)
                .lat(lat)
                .lng(lng)
                .bboxSouth(south)
                .bboxWest(west)
                .bboxNorth(north)
                .bboxEast(east)
                .landmarkDescription(description)
                .difficulty(difficulty)
                .emoji(emoji)
                .build();
    }
}


